require "#{Rails.root}/lib/analyze"

class User
  include MongoMapper::Document
  key :name, String

  #include Analyze
  extend Analyze

  def initialize

  end

  def self.brand
    self.brand_affinity
 #{"status"=>"OK", "usage"=>"By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html", "totalTransactions"=>"1", "language"=>"english", "docSentiment"=>{"score"=>"-0.561518", "type"=>"negative"}}

  end

end
