require "#{Rails.root}/lib/analyze"

class User
  include MongoMapper::Document
  key :name, String
  key :nickname, String
  key :provider, String
  key :uid, String

  many :tweets

  extend Analyze

  def initialize
  end

  def self.brand
    self.brand_affinity
 #{"status"=>"OK", "usage"=>"By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html", "totalTransactions"=>"1", "language"=>"english", "docSentiment"=>{"score"=>"-0.561518", "type"=>"negative"}}
  end

  def self.create_with_omniauth(auth)
    user = User.new
    user.provider = auth['provider']
    user.uid = auth['uid']
    if auth['info']
      user.name = auth['info']['name'] || ""
      user.nickname = auth['info']['nickname'] || ""
    end
    user.save!
    user
  end

  def user_params
    params.require(:user).permit(:name)
  end

end
